---
kind: pipeline
type: docker
name: publish

steps:
- name: publish docker image
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    group: publish
    registry: quay.io
    repo: quay.io/presslabs/light-k8s-deploy-tools
    auto_tag: true
    username: presslabs+drone
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_TOKEN
  when:
    event:
      - tag
      - push

trigger:
  ref:
    - refs/tags/**
    - refs/heads/master
---
kind: signature
hmac: 7f5d570180845ff23340d7d94bb6f0fadd131de699fd19f8304132e21361e8d9

...
